// Shark Naming - Shuffled
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

var sharkname = [
    "Bridget",
    "Nixs",
    "Salve",
    "Sharkie",
    "Jeff the Landshork",
    "Sven",
    "Jerry",
    "Ian",
    "Erin",
    "Lemon",
    "Shylo",
    "Markiplier",
    "Mrs Lovett",
    "Pip",
    "Vida",
    "Billie Eilish",
    "Melli",
    "Greg",
    "Fudge",
    "Blaj",
    "Cheese",
    "Yoshi",
    "Kirby",
    "Alex",
    "Nicole",
    "Shorky",
    "Armando",
    "Wendy",
    "Alex",
    "Clear",
    "Freddy Fazbear",
    "Frankenstein",
    "Connor",
    "Jasper",
    "Kelly",
    "Katie",
    "Samantha",
    "Mabel",
    "The Doctor",
    "Bruce",
    "Lumpy",
    "Alora",
    "Sharkie",
    "Sharkspeare",
    "Tintin",
    "Ivan",
    "Ncuti",
    "Jeffery",
    "Bob",
    "Magnus",
    "Corin",
    "Same-san",
    "Samekiati",
    "Blåhaj McBlåhajface",
    "Dr. Jesus",
    "Jörs",
    "Chips",
    "Neko",
    "Blåhaj McBlåhajface",
    "Sharkgaydo",
    "Mike",
    "Comic Sans",
    "Sharky Mc Shark Face",
    "Squish",
    "Violet",
    "Sock",
    "Bob",
    "Mr Showteeth",
    "Fergle",
    "Tilly",
    "Salestia",
    "Sky",
    "Derek",
    "Olly",
    "Demitri",
    "Jonah",
    "Olha",
    "Bernard",
    "Foxy",
    "Scaramouche",
    "Henry",
    "Kevin",
    "Sharkie",
    "Fin / Finley",
    "Bradley",
    "Sammie",
    "Brucie",
    "Andrew",
    "TERFBANE",
    "The Late Archbiship Desmond Tutu",
    "Bernie",
    "Greg",
    "Brachy",
    "Ciy",
    "Fishy",
    "The Duke",
    "Desmond",
    "Chompy Chomps",
    "Chomy Chomps",
    "Nom Noms",
    "Mork.",
    "Sophie",
    "Shork",
    "Barry",
    "Fin",
    "John",
    "Seraia",
    "Riptide",
    "Devo",
    "Shredder",
    "Ponyo",
    "Batholomew",
    "Wonky",
    "Beep",
    "Boop",
    "Larry",
    "Oswald",
    "Bluey",
    "Bluey",
    "Bruce",
    "Anchor",
    "Chum",
    "Anchor",
    "Steven",
    "Cheder",
    "Kimi",
    "Kimi",
    "Shark",
    "Kimi",
    "Bob",
    "Zoe",
    "Sharky",
    "Bazinga",
    "Bluey",
    "Bruce",
    "Day",
    "Night",
    "Bruno Mars",
    "Mark",
    "Cheesecake",
    "Peirce",
    "Icey",
    "Freida",
    "Weidi",
    "Megan",
    "Alexandra",
    "Tony Perry",
    "Victor Vincent Eventes",
    "Loni Robinson",
    "Tank",
    "Noah",
    "Boaty Mc Boatface",
    "Derek",
    "Kirishima",
    "Azura",
    "Kazuichi Soda",
    "Damion",
    "Bruce",
    "Albie",
    "Charmy",
    "Sharon",
    "Skye",
    "Emily",
    "Dylan",
    "Haj",
    "Minnow",
    "Mr Blue",
    "Mrs Shark",
    "Dianne",
    "Dave",
    "Bob",
    "Queen McFishface",
    "Cheese",
    "Steven",
    "Biscuit",
    "Bibble",
    "Shark",
    "Bubble the Shark",
    "Jaws",
    "Sir Regivus the Third",
    "Bod",
    "Sampson",
    "Egg",
    "Sam",
    "Billy",
    "Sir Pentious",
    "Sir Bartholomew III",
    "POD",
    "Sharky",
    "Wetsuit",
    "Lizzy",
    "Spike",
    "Brucie",
    "Jawgina",
    "Ikea",
    "Meatball",
    "Sven",
    "Shark",
    "S",
    "Bruce",
    "Mr Gei",
    "Skrunkle",
    "Spongebob",
    "Glen",
    "Fin",
    "Waffle",
    "Fred",
    "Bill of willtbaquil",
    "Fishstick",
    "Blahaj",
    "Geoffrey Billingham the 7th",
    "Joe",
    "Sharky McSharkface",
    "Fin",
    "Bruce",
    "Finn",
    "Ed",
    "Murphy",
    "Frank",
    "Gumball",
    "Polymorth",
    "Fransixo",
    "James",
    "Spriryo",
    "Craig",
    "Helga",
    "Alan",
    "Sour Cream",
    "Gummy",
    "Minnow",
    "Silly :3",
    "Cora",
    "Neo",
    "Bob",
    "Opear",
    "Mc Shark Face",
    "Mr TEETHY",
    "Micheal Jackson",
    "Mr Swim",
    "The Egg Cracker",
    "Dougal",
    "Clive",
    "Simon ♥",
    "Sophie",
    "Leo",
    "Mr Gorman",
    "Tootie",
    "Toothless",
    "Floof",
    "Jimmy",
    "Jerremy Beremy",
    "Sharka Khem",
    "Mercedes",
    "Charlie",
    "Gherkin",
    "Keith",
    "Jerremy Beremy",
    "Caz",
    "Alysha",
    "Adi",
    "Bruce",
    "Mr Toes",
    "Flo",
    "Steve",
    "Bob",
    "Ivan",
    "Sharky Jr 2",
    "Bruce",
    "Jaws",
    "Beef Taco Esq",
    "Warhead",
    "Boop",
    "Nevy",
    "Bluey",
    "Frog",
    "Salad",
    "Potato",
    "Mr Chomps",
    "Kaylee",
    "Ananova",
    "Doll",
    "Kyra",
    "Asta",
    "Vi",
    "Pasta",
    "Big Chungus",
    "Slab Bulkhead",
    "Tank",
    "Daisy",
    "Jeffrey",
    "Iris",
    "Malang",
    "Massaneh",
    "Hammer",
    "Ava",
    "Keira",
    "Lovely",
    "Angle Grinder",
    "Enfys",
    "Huelwen",
    "Peter",
    "Joushua K",
    "Jaime Preciado"
];

function changeText() {
    // Shuffle the array
    shuffle(sharkname);

    // Get the first name in the shuffled list
    var firstSharkName = sharkname[0];

    // Display the first name in the shuffled list
    $('span').html(firstSharkName);

    // Call this function again after 2 seconds
    setTimeout(changeText, 2000);
}

// Start the cycle
changeText();
